GET http://localhost:3759/user

###

GET http://localhost:3759/user/test@gmail.com

###

POST http://localhost:3759/user
Content-Type: application/json

{
    "name": "Zno",
    "email": "test2@gmail.com",
    "password": "1234"
}

###

PATCH http://localhost:3759/user/635bd22f4808257bf1cbdb05
Content-Type: application/json

{
    "name": "ZnoKunG"
}

###

DELETE http://localhost:3759/user/635bce1c2b4e86da82cd5f95

### 

DELETE http://localhost:3759/user?confirm=true